#ifndef _TUSB_CONFIG_H_
#define _TUSB_CONFIG_H_

#define CFG_USB_BULK_ENDPOINT_SIZE 64 //max 64 bytes

#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_VENDOR_RX_BUFSIZE CFG_USB_BULK_ENDPOINT_SIZE
#define CFG_TUD_VENDOR_TX_BUFSIZE CFG_USB_BULK_ENDPOINT_SIZE
#define CFG_TUD_VENDOR 1

#endif /* _TUSB_CONFIG_H_ */